export const FETCH_APPOINTMENTS_START = 'FETCH_APPOINTMENTS_START';
export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS';
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
export const FETCH_APPOINTMENTS_ERROR = 'FETCH_APPOINTMENTS_ERROR';

export const SAVE_APPOINTMENT = 'SAVE_APPOINTMENT';
export const SAVE_APPOINTMENT_SUCCESS = 'SAVE_APPOINTMENT_SUCCESS';
export const SAVE_APPOINTMENT_ERROR = 'SAVE_APPOINTMENT_ERROR';
export const RESET_FORM = 'RESET_FORM';